# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post", "paper", "old", "announcement"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2025
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "🍥"
subtitle = "My Personal Site built with Hugo at 17 years old"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "All rights reserved"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "xieyuen-org/xieyuen-org.github.io"
repoID = "R_kgDOP9lsOg"
category = "Announcements"
categoryID = "DIC_kwDOP9lsOs4CwV2A"
mapping = "pathname"
lightTheme = "light"
darkTheme = "dark"
reactionsEnabled = 1
emitMetadata = 0
lang = "zh-CN"

# <script src="https://giscus.app/client.js"
#         data-repo="xieyuen-org/xieyuen-org.github.io"
#         data-repo-id="R_kgDOP9lsOg"
#         data-category="Announcements"
#         data-category-id="DIC_kwDOP9lsOs4CwV2A"
#         data-mapping="pathname"
#         data-strict="0"
#         data-reactions-enabled="1"
#         data-emit-metadata="0"
#         data-input-position="bottom"
#         data-theme="preferred_color_scheme"
#         data-lang="zh-CN"
#         crossorigin="anonymous"
#         async>
# </script>
